sudo: required

language: java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

install:
  - gimme 1.9
  - . $HOME/.gimme/envs/go1.9.env
  - go get github.com/dedis/Coding || true
  # Because we are using "language: java" the "git clone" is not in the
  # GOPATH. So make a copy of it over where it is supposed to be.
  - git clone . `go env GOPATH`/src/github.com/dedis/lleap
  - (cd `go env GOPATH`/src/github.com/dedis/lleap && go get -t ./... )

script:
  # the collections package does not pass lint, disable test_lint for now
  - make test_fmt
  - make docker docker_test
  - (cd `go env GOPATH`/src/github.com/dedis/lleap && go test -v -short $(go list ./... | grep -v /vendor/) )
  # the java test needs conodes to be running, ideally we'd like to manage that in the java code
  - make docker_run
  - (cd external/java; mvn test)

notifications:
email: false
